### ISSUE TITLE
System crashes/hangs when running qemu-img convert

### ISSUE THREAD

**Issue by cmdaltr** [ezaspy/elrond#18]
Currently unable to convert VMDK images to raw using qemu-img. Issue has been raised on GitLab: https://gitlab.com/qemu-project/qemu/-/issues/1216
If anyone knows of a workaround, please let me know/contribute.

**Comment by ezaspy** [comment]
Currently unable to convert VMDK images to raw using qemu-img. Issue has been raised on GitLab.
If anyone knows of a workaround, please let me know/contribute.

**Comment by cmdaltr** [comment]
Now leveraging the following solution to hunt the VMDK directly - i.e. without converting
```
sudo modprobe nbd
sudo qemu-nbd -r -c /dev/nbd1 <DISK>.vmdk
sudo fdisk -l /dev/nbd1
sudo mount /dev/nbd1p3 /mnt/elrond_mount
```
