### ISSUE TITLE
Segmented E01 images

### ISSUE THREAD

**Issue by cmdaltr** [ezaspy/elrond#4]
elrond cannot mount the image if Encase File Format is split into multiple files (E01, E02, E03, etc.)

**Comment by ezaspy** [comment]
elrond cannot mount the image if Encase File Format is split into multiple files (E01, E02, E03, etc.)

**Comment by cmdaltr** [comment]
Fixed - https://github.com/ezaspy/elrond/commit/30fc094e451c0ef57dadfd361d561661cd96ace3
